---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.ARENA_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.ARENA_NAME}}"
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.ARENA_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.ARENA_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.ARENA_NAME}}"
        image: "{{.ARENA_IMAGE}}:{{.ARENA_TAG}}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: REDIS_PORT
            value: "{{.REDIS_PORT}}"
          - name: REDIS_SSL
            value: "{{.REDIS_SSL}}"
          - name: REDIS_URI
            value: "{{.REDIS_URL}}"
          - name: REDIS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{.ARENA_NAME}}"
                key: redisToken
          - name: ARENA_PORT
            value: "{{.ARENA_PORT}}"
      volumes:
      - name: certs
        secret:
          secretName: "{{.ARENA_NAME}}-pod-tls"
